### ISSUE TITLE
[v1.6.0] possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by xxsnakerxx** [rnpm/rnpm#139] opened 2016-04-07 10:13 UTC
When I run `rnpm link` I get error

``` javascript

(node) warning: possible EventEmitter memory leak detected. 11 end listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at ReadStream.addListener (events.js:252:17)
    at ReadStream.Readable.on (_stream_readable.js:673:33)
    at new Interface (readline.js:129:11)
    at Object.exports.createInterface (readline.js:22:10)
    at Object.Interface.createInterface (/Users/xxsnakerxx/Works/Eris/qplatform/frontend/RN/qroutes/node_modules/readline2/index.js:34:21)
    at module.exports (/Users/xxsnakerxx/Works/Eris/qplatform/frontend/RN/qroutes/node_modules/inquirer/lib/ui/baseUI.js:14:30)
    at new module.exports (/Users/xxsnakerxx/Works/Eris/qplatform/frontend/RN/qroutes/node_modules/inquirer/lib/ui/prompt.js:15:8)
    at Object.promptModule [as prompt] (/Users/xxsnakerxx/Works/Eris/qplatform/frontend/RN/qroutes/node_modules/inquirer/lib/inquirer.js:27:14)
    at /Users/xxsnakerxx/Works/Eris/qplatform/frontend/RN/qroutes/node_modules/rnpm-plugin-link/src/pollParams.js:8:12
    at module.exports.Promise (/Users/xxsnakerxx/Works/Eris/qplatform/frontend/RN/qroutes/node_modules/rnpm-plugin-link/src/pollParams.js:3:33)
(node) warning: possible EventEmitter memory leak detected. 11 drain listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at WriteStream.addListener (events.js:252:17)
    at WriteStream.Readable.on (_stream_readable.js:673:33)
    at MuteStream.Stream.pipe (stream.js:45:8)
    at MuteStream.pipe (/Users/xxsnakerxx/Works/Eris/qplatform/frontend/RN/qroutes/node_modules/mute-stream/mute.js:89:32)
    at Object.Interface.createInterface (/Users/xxsnakerxx/Works/Eris/qplatform/frontend/RN/qroutes/node_modules/readline2/index.js:30:6)
    at module.exports (/Users/xxsnakerxx/Works/Eris/qplatform/frontend/RN/qroutes/node_modules/inquirer/lib/ui/baseUI.js:14:30)
    at new module.exports (/Users/xxsnakerxx/Works/Eris/qplatform/frontend/RN/qroutes/node_modules/inquirer/lib/ui/prompt.js:15:8)
    at Object.promptModule [as prompt] (/Users/xxsnakerxx/Works/Eris/qplatform/frontend/RN/qroutes/node_modules/inquirer/lib/inquirer.js:27:14)
    at /Users/xxsnakerxx/Works/Eris/qplatform/frontend/RN/qroutes/node_modules/rnpm-plugin-link/src/pollParams.js:8:12
    at module.exports.Promise (/Users/xxsnakerxx/Works/Eris/qplatform/frontend/RN/qroutes/node_modules/rnpm-plugin-link/src/pollParams.js:3:33)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at WriteStream.addListener (events.js:252:17)
    at WriteStream.Readable.on (_stream_readable.js:673:33)
    at MuteStream.Stream.pipe (stream.js:79:8)
    at MuteStream.pipe (/Users/xxsnakerxx/Works/Eris/qplatform/frontend/RN/qroutes/node_modules/mute-stream/mute.js:89:32)
    at Object.Interface.createInterface (/Users/xxsnakerxx/Works/Eris/qplatform/frontend/RN/qroutes/node_modules/readline2/index.js:30:6)
    at module.exports (/Users/xxsnakerxx/Works/Eris/qplatform/frontend/RN/qroutes/node_modules/inquirer/lib/ui/baseUI.js:14:30)
    at new module.exports (/Users/xxsnakerxx/Works/Eris/qplatform/frontend/RN/qroutes/node_modules/inquirer/lib/ui/prompt.js:15:8)
    at Object.promptModule [as prompt] (/Users/xxsnakerxx/Works/Eris/qplatform/frontend/RN/qroutes/node_modules/inquirer/lib/inquirer.js:27:14)
    at /Users/xxsnakerxx/Works/Eris/qplatform/frontend/RN/qroutes/node_modules/rnpm-plugin-link/src/pollParams.js:8:12
    at module.exports.Promise (/Users/xxsnakerxx/Works/Eris/qplatform/frontend/RN/qroutes/node_modules/rnpm-plugin-link/src/pollParams.js:3:33)
(node) warning: possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at WriteStream.addListener (events.js:252:17)
    at WriteStream.Readable.on (_stream_readable.js:673:33)
    at MuteStream.Stream.pipe (stream.js:101:8)
    at MuteStream.pipe (/Users/xxsnakerxx/Works/Eris/qplatform/frontend/RN/qroutes/node_modules/mute-stream/mute.js:89:32)
    at Object.Interface.createInterface (/Users/xxsnakerxx/Works/Eris/qplatform/frontend/RN/qroutes/node_modules/readline2/index.js:30:6)
    at module.exports (/Users/xxsnakerxx/Works/Eris/qplatform/frontend/RN/qroutes/node_modules/inquirer/lib/ui/baseUI.js:14:30)
    at new module.exports (/Users/xxsnakerxx/Works/Eris/qplatform/frontend/RN/qroutes/node_modules/inquirer/lib/ui/prompt.js:15:8)
    at Object.promptModule [as prompt] (/Users/xxsnakerxx/Works/Eris/qplatform/frontend/RN/qroutes/node_modules/inquirer/lib/inquirer.js:27:14)
    at /Users/xxsnakerxx/Works/Eris/qplatform/frontend/RN/qroutes/node_modules/rnpm-plugin-link/src/pollParams.js:8:12
    at module.exports.Promise (/Users/xxsnakerxx/Works/Eris/qplatform/frontend/RN/qroutes/node_modules/rnpm-plugin-link/src/pollParams.js:3:33)
(node) warning: possible EventEmitter memory leak detected. 11 keypress listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at ReadStream.addListener (events.js:252:17)
    at ReadStream.Readable.on (_stream_readable.js:673:33)
    at new Interface (readline.js:128:11)
    at Object.exports.createInterface (readline.js:22:10)
    at Object.Interface.createInterface (/Users/xxsnakerxx/Works/Eris/qplatform/frontend/RN/qroutes/node_modules/readline2/index.js:34:21)
    at module.exports (/Users/xxsnakerxx/Works/Eris/qplatform/frontend/RN/qroutes/node_modules/inquirer/lib/ui/baseUI.js:14:30)
    at new module.exports (/Users/xxsnakerxx/Works/Eris/qplatform/frontend/RN/qroutes/node_modules/inquirer/lib/ui/prompt.js:15:8)
    at Object.promptModule [as prompt] (/Users/xxsnakerxx/Works/Eris/qplatform/frontend/RN/qroutes/node_modules/inquirer/lib/inquirer.js:27:14)
    at /Users/xxsnakerxx/Works/Eris/qplatform/frontend/RN/qroutes/node_modules/rnpm-plugin-link/src/pollParams.js:8:12
    at module.exports.Promise (/Users/xxsnakerxx/Works/Eris/qplatform/frontend/RN/qroutes/node_modules/rnpm-plugin-link/src/pollParams.js:3:33)
(node) warning: possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at process.addListener (events.js:252:17)
    at module.exports (/Users/xxsnakerxx/Works/Eris/qplatform/frontend/RN/qroutes/node_modules/inquirer/lib/ui/baseUI.js:24:11)
    at new module.exports (/Users/xxsnakerxx/Works/Eris/qplatform/frontend/RN/qroutes/node_modules/inquirer/lib/ui/prompt.js:15:8)
    at Object.promptModule [as prompt] (/Users/xxsnakerxx/Works/Eris/qplatform/frontend/RN/qroutes/node_modules/inquirer/lib/inquirer.js:27:14)
    at /Users/xxsnakerxx/Works/Eris/qplatform/frontend/RN/qroutes/node_modules/rnpm-plugin-link/src/pollParams.js:8:12
    at module.exports.Promise (/Users/xxsnakerxx/Works/Eris/qplatform/frontend/RN/qroutes/node_modules/rnpm-plugin-link/src/pollParams.js:3:33)
    at dependency.config.params (/Users/xxsnakerxx/Works/Eris/qplatform/frontend/RN/qroutes/node_modules/rnpm-plugin-link/src/link.js:106:13)
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:146:18)

```

And next nothing happens

My RN packages

``` javascript

    "react-native-mapbox-gl": "^3.0.0",
    "react-native-cookies": "^1.0.0",
    "react-native-device-info": "^0.9.1",
    "react-native-image-picker": "^0.18.10",
    "react-native-linear-gradient": "^1.5.2",
    "react-native-mock": "0.0.7",
    "react-native-side-menu": "^0.18.0",
    "react-native-social-auth": "^0.4.0",
    "react-native-testfairy": "^1.7.0",
    "react-native-vector-icons": "^1.3.2",

```

`rnpm@1.5.5` works fine!!!

**Comment by Kureev** [comment] 2016-04-07 11:23
Hi @xxsnakerxx! Which node version are you using?

**Comment by xxsnakerxx** [comment] 2016-04-07 11:26
Hi @Kureev! I'm using node `v5.10.1`

**Comment by Kureev** [comment] 2016-04-07 11:33
That's interesting, because it seems to be a known bug with inquirer for the old node environments: https://github.com/SBoudrias/Inquirer.js/issues/115

**Comment by Kureev** [comment] 2016-04-07 11:34
I'll try to reproduce your error today-tomorrow and give you some feedback about it. Thanks for reporting it!

**Comment by grabbou** [comment] 2016-05-03 11:14
Did you have any luck with reproducing it? I didn't. I think it's wise to close this as it's non-rnpm issue and optionally re-open the inquirer ticket if it's still the case.

**Comment by xxsnakerxx** [comment] 2016-05-04 08:17
Hi! I can't reproduce it too.
`rnpm 1.7.0`
`node 6.0.0`

**Comment by Kureev** [comment] 2016-05-04 11:29
I wasn't able to reproduce it :(

**Comment by Kureev** [comment] 2016-05-04 11:29
So, if nobody can reproduce it anymore, I propose to close it.

**Closed by Kureev** 2016-05-04 11:29 UTC
Labels: bug
