### ISSUE TITLE
rnpm ios link failure with CocoaPods

### ISSUE THREAD

**Issue by GantMan** [rnpm/rnpm#111] opened 2016-03-16 03:44 UTC
Not sure what's up, but this keeps happening when I try to use `rnpm` with anything ios
<img width="764" alt="screen shot 2016-03-15 at 10 43 07 pm" src="https://cloud.githubusercontent.com/assets/997157/13801397/61978bc2-eaff-11e5-9ac7-b03810486b56.png">

**Comment by grabbou** [comment] 2016-03-16 06:38
In general? Or in this project? What's the xcode library version? (can you check its package.json)? And xcode (app) itself? I am hoping there was no minor breaking change release.

**Comment by GantMan** [comment] 2016-03-18 19:00
This is on a project that has grown since RN 0.14, with tons of manual upgrades.  But it works and ships to the store just fine.

Xcode App: Version 7.2.1 (7C1002) - everything is latest for Xcode.

just upgraded to v1.5.2 same exact output.

Let me know if you want me to run any commands to gather info.

**Comment by grabbou** [comment] 2016-03-19 08:56
I would just love your `.xcodeproj` to get (could you send it zipped to my email? It's under my profile). I think it's something underlying xcode library is not supporting that I think we can submit a PR to fix!

**Comment by hvsy** [comment] 2016-03-23 07:26
@grabbou, I get same error after use new CocoaPods to install dependencies. I found CocoaPods will convert the "xcodeproj" file to xml format. and then the library node-xcode can't handle it. so it will raise the error.

**Comment by GantMan** [comment] 2016-03-23 14:11
this makes sense.  I'm using CocoaPods as well.

**Comment by grabbou** [comment] 2016-03-23 16:58
Okey, thanks for the reports! I will investigate and ideally let's patch it in node-xcode itself. I have that feeling it's because of their parser not having all possible expressions defined in some places.

**Comment by grabbou** [comment] 2016-03-28 19:51
Just to update - we are on the email with @GantMan checking out what might be causing this. I was unable to reproduce that using the files he sent me using latest master, so going to close it as we are going to continue fixing via emails. It might be the case that we have fixed it accidentally in the meantime.

If anyone else encounters this issue - please feel free to ping me so I can reopen.

**Comment by grabbou** [comment] 2016-03-28 20:06
Sounds like this might be this -> https://github.com/CocoaPods/CocoaPods/issues/1275#issuecomment-22391200

Can you confirm that this is the case? If yes - I am happy to add a warning with steps how to fix that.

**Comment by marcshilling** [comment] 2016-03-29 16:25
How can I make `rnpm` link the library in my project under Libraries and not under Pods/Libraries?

**Comment by grabbou** [comment] 2016-03-29 17:16
Oh, that's a good question. We shouldn't even check in pods group. I think it might be an issue when two or more groups with the same name are created. I'll try to reproduce it and send a fix.

**Comment by grabbou** [comment] 2016-03-30 06:52
@marcshilling that was indeed an issue, see PR linked ^ for a fix (will land today)

**Comment by marcshilling** [comment] 2016-03-30 13:54
Cool, thanks!

**Comment by grabbou** [comment] 2016-03-31 06:07
2nd thing is now released https://twitter.com/grabbou/status/715419502918414336. Please update rnpm and let me know :)

Also - re: @GantMan original issue - going to close this one for now since it looks like it's that xml issue. Let me know if that's it - if not, happy to reopen.

**Closed by grabbou** 2016-03-31 06:07 UTC
Labels: iOS, needs more information

**Comment by GantMan** [comment] 2016-03-31 22:32
@grabbou  it works now!  Thanks :)
