### ISSUE TITLE
ENOENT for commands-prelink

### ISSUE THREAD

**Issue by miqmago** [rnpm/rnpm#146] opened 2016-04-23 11:07 UTC
I would like to contribute to this react native plugin https://github.com/yamill/react-native-orientation. Maybe it's not the correct approach and if there is a better one I would like to know it as well (as there may be some usefull commands similar to `packageInstance` but I can't see in documentation):

It needs to modify MainActivity.java and insert this piece of code:

```java
    @Override
    public void onConfigurationChanged(Configuration newConfig) {
        super.onConfigurationChanged(newConfig);
        Intent intent = new Intent("onConfigurationChanged");
        intent.putExtra("newConfig", newConfig);
        this.sendBroadcast(intent);
    }
```

I've tried to modify `node_modules/react-native-orientation/package.json` with:
```json
  "rnpm": {
    "commands": {
      "prelink": "./rnpm/prelink"
    }
  },
```

And also create a file in `node_modules/react-native-orientation/rnpm/prelink.js`:
```javascript
console.log("Hey!");
module.exports = function link(config, args) {
    console.log("Maybe here... Hey!");
};
```

What I'm getting is:
```bash
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn ./rnpm/prelink.js ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:968:3
```

**Comment by Kureev** [comment] 2016-04-23 19:21
Hi @miqmago!

Strange to see this output. This code snippet
```json
  "rnpm": {
    "commands": {
      "prelink": "./rnpm/prelink"
    }
  },
```
should invoke `./rnpm/prelink`, not `./rnpm/prelink.js`, but in your output I see that rnpm tries to spawn `prelink.js`, that confuses me a bit. First of all try to add `.js` to `./rnpm/prelink` path and let me know if that helps.

P.S. Don't forget to add executable rights to this file (`chmod +x ./rnpm/prelink.js`).

**Comment by miqmago** [comment] 2016-04-23 19:30
@Kureev I had already tried with `.js` extension with same result.
Also ls for rnpm:

```javascript
drwxrwxrwx 1 miqmago staff 32768 Apr 23 21:28 .
drwxrwxrwx 1 miqmago staff 32768 Apr 23 21:28 ..
-rwxrwxrwx 1 miqmago staff   110 Apr 23 21:28 prelink.js
```

**Comment by miqmago** [comment] 2016-04-23 19:39
Hmm... That made me think. This is an npm module so I'm executing rnpm from project path. I've made some tests and it seems that it is a path issue: tried to place relative path to project (and full path with same result) in package.json and the result is this one:

```json
  "rnpm": {
      "commands": {
          "prelink": "./node_modules/react-native-orientation/rnpm/prelink.js"
      }
  }
```

```bash
Error: Error occured during executing "./node_modules/react-native-orientation/rnpm/prelink.js" command
    at ChildProcess.prelink (/Users/miqmago/.nvm/versions/node/v4.4.2/lib/node_modules/rnpm/src/makeCommand.js:19:15)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

It seems to find the file, the problem here is what if user changes the location of `node_modules`? (It will break).

Also the error I'm not undesrtanding why.

**Comment by Kureev** [comment] 2016-04-25 06:09
Well, what you see here is that your script exits with error code.

The problem is in the script itself. Can you post a script you're trying to run?

**Comment by miqmago** [comment] 2016-04-25 07:52
@Kureev the script is the test initial one:

```javascript
console.log("Hey!");
module.exports = function link(config, args) {
    console.log("Maybe here... Hey!");
};
```

Also tried to remove initial console.log

**Comment by Kureev** [comment] 2016-04-25 08:15
You need to add
```
#!/usr/local/bin/node
```
in the head of your file if you want to make it executable like this.

**Comment by grabbou** [comment] 2016-04-25 08:23
@miqmago once you sort it out, would you mind sending a PR to improve the docs?

**Comment by miqmago** [comment] 2016-04-25 09:01
@grabbou Sure to make a PR when I have the knowledge :smile: 
@Kureev Thanks, that seems to work.

I need little more help: right now it gets executed as a plain javascript file, not as a module, is it right?  In that case, how can I access to project files? (meaning MainActivity.java, Info.plist, etc...)
This script file seems to me a little bit like (let me introduce our old friend) cordova hooks. They have some environment variables where the script name is being passed, etc. Is it the same case here?

Also another question is, are there some exports that are/could be automatically called inside this script (for example when linking ios/android, when modifying a file, or similar). Maybe is a great feature to be implemented in future that would make plugin developers live's easier.

```javascript
#!/usr/local/bin/node
console.log("Hey");
console.log(process);
module.exports = function link(config, args) {
    console.log("Maybe here... Hey!");
};
```

Outputs `"Hey"` and process variable, but link function is never being called.

----

Just to clarify the concepts, in my understanding, cordova plugin system is very mature and complete and there are a bunch of features and things that can be done when a plugin is installed: you can define which dependencies the plugin has (frameworks, gradle, other plugins), which files/assets the plugin uses and where should they be placed, android manifest permissions, so on so on, and everything is defined in a `plugin.xml` file. To make the simil, here it would be `package.json`, right? Don't know if this has been taken in care in the goals of `rnpm` but in my opinion this `prelink, postlink, etc` system could be the baby start point, isn't it?

This rnpm plugin system seems to me a little bit like cordova hook system before plugin install, before build, etc... but the differences are that they get executed for every `cordova` cli and right now we here we only have `prelink` and `postlink` that gets executed when `rnpm link` is explicitly called, right?

I know, I know, react-native is not cordova, but it's still good job to be done and there are good things thad can be imported from... :smile:

**Comment by miqmago** [comment] 2016-04-27 16:03
Any help with this?

**Comment by Kureev** [comment] 2016-05-13 03:58
> I need little more help: right now it gets executed as a plain javascript file, not as a module, is it right? In that case, how can I access to project files? (meaning MainActivity.java, Info.plist, etc...)

Yes, correct. 
Well, unfortunately, we don't provide anything for managing these files. It's just a script. Similar to `npm scripts`. You can take a look how realm guys do it: https://github.com/realm/realm-js/blob/master/scripts/rnpm-postlink.js

> Also another question is, are there some exports that are/could be automatically called inside this script (for example when linking ios/android, when modifying a file, or similar)

Nope, not yet. Theoretically, rnpm should cover all common cases for linking native deps (like native deps etc). Hooks has been designed to allow library authors make a very specific scripts which are considered as a non-standard actions for linking.

I believe, the subj has been solved, so closing it. Feel free to keep asking your questions there.

P.S. Sorry for the late response.

**Closed by Kureev** 2016-05-13 03:58 UTC
Labels: help wanted
