### ISSUE TITLE
Linking Android dependancies not working

### ISSUE THREAD

**Issue by DVassilev** [rnpm/rnpm#77] opened 2016-01-23 15:04 UTC
When I try to link react-native-linear-gradient it tells me that the Android dependancy is 'already linked'. This, however, is incorrect. Any idea as to what this may be caused by?

**Comment by Kureev** [comment] 2016-01-23 17:42
Which react-native version are you using?

**Comment by DVassilev** [comment] 2016-01-24 05:06
@Kureev
react-native-cli: 0.1.10
react-native: 0.18.1
rnpm: 1.4.1
npm: 2.14.7
node: 4.2.3

**Comment by Psykar** [comment] 2016-01-24 23:07
Looks like the changes to MainActivity.java have changed in 0.18.1

``` 
@@ -34,6 +36,8 @@ public class MainActivity extends ReactActivity {
     @Override
     protected List<ReactPackage> getPackages() {
       return Arrays.<ReactPackage>asList(
-        new MainReactPackage());
+        new MainReactPackage(),
+        new CookieManagerPackage()
+        );
     }
 }
```

Where as previously it was 
```
@@ -30,6 +31,7 @@ public class MainActivity extends Activity implements DefaultHardwareBackBtnHand
                 .setBundleAssetName("index.android.bundle")
                 .setJSMainModuleName("index.android")
                 .addPackage(new MainReactPackage())
+                .addPackage(new CookieManagerPackage())
                 .addPackage(mReactNativePushNotificationPackage)
                 .setUseDeveloperSupport(BuildConfig.DEBUG)
                 .setInitialLifecycleState(LifecycleState.RESUMED)
```

**Comment by Psykar** [comment] 2016-01-24 23:20
This looks like it's fixed here: https://github.com/rnpm/rnpm-plugin-link/pull/22

**Comment by Kureev** [comment] 2016-01-24 23:32
It is, going to merge it soon, need 1 hour more

**Comment by DVassilev** [comment] 2016-03-04 02:46
@Kureev this is still an issue for me, has not been fixed.

**Comment by Kureev** [comment] 2016-03-04 08:43
@DVassilev update your `rnpm-plugin-link`, the issue should be solved in `1.5.5`

**Comment by DVassilev** [comment] 2016-03-04 09:16
@Kureev How do I do that?

**Comment by Kureev** [comment] 2016-03-04 09:25
@DVassilev depends on how you installed `rnpm`. If we installed it globally, run `npm i rnpm -g` again and it'll update your rnpm version with `rnpm-plugin-link`. Otherwise, you can just run `npm i rnpm-plugin-link -g` and update only a `rnpm-plugin-link`. If you're using a local installation, run the same commands without `-g` flag.

**Comment by DVassilev** [comment] 2016-03-04 12:32
@Kureev I updated and still it doesn't link android. It says already linked.

**Comment by Kureev** [comment] 2016-03-04 13:48
@DVassilev remove `:react-native-vector-icons` from your build.gradle file and try again.

**Comment by DVassilev** [comment] 2016-03-04 14:04
@Kureev how did you know that is the package I am installing? I'll try it out
tomorrow morning and let you know.

On Sat, Mar 5, 2016 at 12:48 AM, Alexey <notifications@github.com> wrote:
@DVassilev [https://github.com/DVassilev] remove :react-native-vector-icons from your build.gradle file and try again.

—
Reply to this email directly or view it on GitHub
[https://github.com/rnpm/rnpm/issues/77#issuecomment-192290806] .[https://github.com/notifications/beacon/AEPX-4qLQoChqWDnpqYAXthsRX7Zba9Mks5pqDgVgaJpZM4HK8B4.gif]

**Comment by grabbou** [comment] 2016-03-19 21:45
Is that still a bug or has it been fixed? :)

**Comment by DVassilev** [comment] 2016-03-24 00:34
@grabbou still seems to be an issue, I have actually stopped using it as has started breaking everything for me once I started adding the FB SDK

**Comment by grabbou** [comment] 2016-04-07 10:00
I can't reproduce this - hopefully someone can jump in later and provide files we can reproduce!

**Comment by Kureev** [comment] 2016-05-13 03:46
Well, we made quite a lot of work on this (I reworked Android link algorithm and @grabbou explained how to link fb sdk (see https://github.com/rnpm/rnpm/issues/144)). Can we close this one, @DVassilev?

**Comment by DVassilev** [comment] 2016-05-18 03:14
@Kureev I stopped using it. I'll attempt to make use of it on my next project and will let you know how it goes.

**Comment by Kureev** [comment] 2016-05-18 12:58
Ok, closing for now

**Closed by Kureev** 2016-05-18 12:58 UTC
Labels: Android, needs response from author
